[package]
name = "git-project"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

clap = { version = "4", features = ["derive"] }
chksum-sha1 = "0.0.0"
similar = "2.4.0"
color-print = "0.3.5"

